Update cache.py
I got  the error
 File "betfairlightweight/streaming/cache.py", line 585, in update_cache
TypeError: update() missing 1 required positional argument: 'active'

after upgrading bflw so this should hopefully fix that.